#UID=$(id -u) GID=$(id -g) docker compose up -d --build
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: juvenal
        uid: 1000
    depends_on:
      - db
    restart: always
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - "8000:80"

  db:
    container_name: db
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./php/data:/var/lib/mysql
    ports:
      - "9906:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
